Feature: Core Script Execution with jbang
  As a Java developer,
  I want to initialize, edit, and run Java scripts using the jbang CLI,
  So that I can quickly execute Java code without complex project setup.

  Scenario: Running a simple Java script
    Given a Java script file "HelloWorld.java" containing a main method that prints "Hello, jbang!"
    When I execute the command "jbang HelloWorld.java"
    Then the standard output should contain "Hello, jbang!"
    And the standard error should be empty

  Scenario: Running a script with dependencies
    Given a Java script file "DepTest.java" that uses "commons-lang3" and prints a reversed string
    And the script "DepTest.java" contains the line "//DEPS org.apache.commons:commons-lang3:3.12.0"
    When I execute the command "jbang DepTest.java"
    Then the standard output should contain the reversed string generated by commons-lang3
    And the standard error should be empty

  Scenario Outline: Passing arguments to a script
    Given a Java script file "ArgPrinter.java" that prints its command-line arguments
    When I execute the command "jbang ArgPrinter.java <arguments>"
    Then the standard output should contain "<expected_output>"
    And the standard error should be empty

    Examples:
      | arguments        | expected_output |
      | hello world      | hello world     |
      | "arg with space" | arg with space  |
      | --option=value   | --option=value  |

  Scenario: Handling script compilation errors
    Given a Java script file "Broken.java" with a syntax error
    When I execute the command "jbang Broken.java"
    Then the command should exit with a non-zero status code
    And the standard error should contain a compilation error message

  Scenario: Handling missing script file
    Given the file "NonExistent.java" does not exist
    When I execute the command "jbang NonExistent.java"
    Then the command should exit with a non-zero status code
    And the standard error should contain a message indicating the file was not found

  Scenario Outline: Running scripts with specific Java versions
    Given a Java script file "VersionCheck.java" that prints the Java version it runs on
    And the script "VersionCheck.java" specifies "//JAVA <java_version>"
    And Java version <java_version> is available on the system
    When I execute the command "jbang VersionCheck.java"
    Then the standard output should indicate it ran with Java version <java_version>
    And the standard error should be empty

    Examples:
      | java_version |
      | 11           |
      | 17           |
      # Add more relevant Java versions as needed

  Scenario: Initializing a new script
    Given an empty directory "my_script_dir"
    When I change the current directory to "my_script_dir"
    And I execute the command "jbang init MyScript.java"
    Then a file named "MyScript.java" should be created
    And the file "MyScript.java" should contain basic runnable Java template code